CREATE TABLE "Opere" (
	"codice"	INTEGER UNIQUE,
	"titolo"	VARCHAR(50) NOT NULL,
	"codM"      INTEGER,
    "codA"      INTEGER,
	PRIMARY KEY("codice" AUTOINCREMENT),
	FOREIGN KEY ("codM") REFERENCES "Musei"("codM") ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY ("codA") REFERENCES "Artisti"("codA") ON UPDATE CASCADE ON DELETE RESTRICT
);
