CREATE TABLE PERICOLOSE AS
SELECT S.Localita, COUNT(S.CodS) AS NumeroIncidenti, SUM(AC.ImportoDelDanno) AS TotaleDanni
FROM SINISTRI AS S, AUTOCOINVOLTE AS AC
WHERE S.CodS = AC.CodS
AND AC.DataRimborso IS NOT NULL
GROUP BY S.Localita
HAVING COUNT(S.CodS) > 5
ORDER BY TotaleDanni DESC;